### ISSUE TITLE
the quest  "Zapped Giants" Gives you an itme called
Zorbin's Ult...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3748] opened 2024-05-08 19:49 UTC
> the quest  "Zapped Giants" Gives you an itme called
Zorbin's Ultra-Shrinker. Upon still  logging out the quets item will vanish from your bag forcing you to quit the quest losing the zapped giants  residue. Please make it so the quest item doesn't vanish when U log out while sitll have the quest active

.go xyz -4596.790000 399.233000 38.418700 1 2.219230

**Comment by zana244** [comment] 2024-09-14 12:11
Hmmm, if you log out you don't lose the quest item on internal. But the item does have a 2h duration, so if you log out for more than that you will lose it. closing as intended
#1659

**Closed as completed by zana244** 2024-09-14 12:11 UTC
Labels: Invalid - Intended / Won't Fix / Blizzlike
