### ISSUE TITLE
Southsea Brigand - (3381)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#395] opened 2024-05-07 07:37 UTC
> These guys can use [Backhand] (spell that stuns) even when fleeing
`.go xyz -1696.450000 -3842.330000 12.007500 1 2.550020`

**Comment by Shadownflame** [comment] 2024-09-05 20:57
Probably fixed with the flee behavior change. I can't reproduce it anymore.

**Closed as completed by Shadownflame** 2024-09-05 20:57 UTC
Labels: Blizzard, Creature, State - Complete
