### ISSUE TITLE
the marred uldic set n uldaman seems to have a weirdly high drop...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6606] opened 2024-05-09 14:11 UTC
> the marred uldic set n uldaman seems to have a weirdly high drop rate

.go xyz 77.299300 216.947000 -54.973600 70 3.608110

**Comment by Shadownflame** [comment] 2024-09-12 14:45
Either gotten lucky or it was resolved with the recent loot updates. Can't reproduce.

**Closed as completed** 2024-09-12 14:44 UTC
Labels: Instance - Dungeon, Invalid - Can't Reproduce, Loot, Items
